spring.application.name=banking-mcp-server
server.port=8081
spring.ai.mcp.server.name=core-banking-governance-hub
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.annotation-scanner.enabled=true
spring.ai.mcp.server.capabilities.tool=true
spring.ai.mcp.server.protocol=STREAMABLE